Курсы,лекции,тесты
mkhomich/projectP21 pull request #3
Opened 2024-04-06 09:03 UTC by MAMBLXON

Начал писать методы Course

2024-04-09 15:36 UTC, mkhomich requested changes

2024-04-09 15:50 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/CourseService.java
> +        dao.getAllcourses();
готово

2024-04-09 15:50 UTC, MAMBLXON commented on src/main/java/ru/top/project/model/Lecture.java
> +    private int numberLecture;
готово

2024-04-18 14:55 UTC, mkhomich requested changes

2024-04-18 16:38 UTC, mkhomich requested changes

2024-04-18 16:38 UTC, mkhomich commented on src/main/java/ru/top/project/dao/Impl/LectureDaoImpl.java
> +        lecture.setId(generateId());
Не генерируй. В будущем это усложнит интеграцию с БД

2024-04-18 16:38 UTC, mkhomich commented on src/main/java/ru/top/project/Service/HomeWorkService.java
> +    public void createHomeWork(HomeWork homeWork) {
То же самое, в случае успешного сохранения возвращай объект

2024-04-18 16:38 UTC, mkhomich commented on src/main/java/ru/top/project/Service/HomeWorkService.java
> +        Map<Integer, HomeWork> homeWorkMap = homeWorkDao.getAllHomeWorks();
Убираем мапу

2024-04-18 16:38 UTC, mkhomich commented on src/main/java/ru/top/project/Service/LectureService.java
> +    public void createLecture(int courseId, Lecture lecture) {
Передавай не айди курса, а объект курса

2024-04-18 16:38 UTC, mkhomich commented on src/main/java/ru/top/project/Service/LectureService.java
> +    public void updateLecture(LectureDaoImpl lecture) {
Зачем передавать поле класс в метод этого же класса?

2024-04-18 16:38 UTC, mkhomich commented on src/main/java/ru/top/project/Service/ReviewsService.java
> +    public List<Reviews> getAllReviewsCourse(int courseId) {
getAllReviewsByCourceId

2024-04-18 16:55 UTC, MAMBLXON commented on src/main/java/ru/top/project/Main.java
> +public abstract class Main {
готово

2024-04-18 16:55 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/HomeWorkService.java
> +package ru.top.project.Service;
готово

2024-04-18 17:08 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/LectureService.java
> +    private final LectureDaoImpl lecture;
готово

2024-04-18 17:08 UTC, MAMBLXON commented on src/main/java/ru/top/project/model/Reviews.java
>  public class Reviews {
готово

2024-04-18 17:08 UTC, MAMBLXON commented on src/main/java/ru/top/project/model/Course.java
> +    private Map<Integer, User> users = new HashMap<>();
готово

2024-04-18 17:09 UTC, MAMBLXON commented on src/main/java/ru/top/project/dataes/CourseData.java
> +    public void displayCourses() {
готово

2024-04-18 17:27 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/LectureDaoImpl.java
> +        lecture.setId(generateId());
готово

2024-04-18 17:30 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/HomeWorkService.java
> +        Map<Integer, HomeWork> homeWorkMap = homeWorkDao.getAllHomeWorks();
готово

2024-04-18 17:31 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/LectureService.java
> +    public void createLecture(int courseId, Lecture lecture) {
готово

2024-04-18 17:34 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/LectureService.java
> +    public void updateLecture(LectureDaoImpl lecture) {
готово

2024-04-18 17:35 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/ReviewsService.java
> +    public List<Reviews> getAllReviewsCourse(int courseId) {
готово

2024-04-18 17:35 UTC, MAMBLXON commented on src/main/java/ru/top/project/Service/HomeWorkService.java
> +    public void createHomeWork(HomeWork homeWork) {
готово

2024-04-18 17:36 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/ReviewsDao.java
> +    void addReview(Reviews review);
готово

2024-04-18 17:49 UTC, MAMBLXON commented on src/main/java/ru/top/project/model/Reviews.java
> +    private int courseById;
готово

2024-04-23 16:45 UTC, mkhomich approved these changes

2024-04-23 16:45 UTC, merged