Курсы,лекции,тесты
mkhomich/projectP21 pull request #7
Opened 2024-04-25 15:40 UTC by MAMBLXON

https://ru.yougile.com/team/f04cc9e23dc1/#PRI-65

2024-05-14 15:18 UTC, mkhomich requested changes

2024-05-14 16:54 UTC, MAMBLXON commented on src/main/java/ru/top/project/Main.java
> +        System.out.println("Введиете id пользователя ");
готово

2024-05-14 16:54 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +            connection = DriverManager.getConnection(
готово

2024-05-14 16:54 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +            results = statement.executeQuery("SELECT * FROM users");
готово

2024-05-14 16:54 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +            results = statement.executeQuery("SELECT * FROM users");
готово

2024-05-14 16:54 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +    public UserDaoJdbcImpl() {
готово

2024-05-14 16:55 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +    public void printData(Integer id) {
готово

2024-05-20 14:40 UTC, mkhomich requested changes

2024-05-21 16:19 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +public abstract class UserDaoJdbcImpl implements UserDao {
готово

2024-05-21 16:20 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +    public BigInteger getUser(BigInteger userId) {
готово

2024-05-21 17:01 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +    private void closeResources(AutoCloseable... resources) {
готово

2024-05-21 17:01 UTC, MAMBLXON commented on src/main/java/ru/top/project/dao/Impl/UserDaoJdbcImpl.java
> +            // Здесь должна быть логика для формирования и возврата списка пользователей
готово

2024-05-21 17:16 UTC, merged